defaults:
  - override hydra/sweeper: optuna

hydra:
  # output_subdir: null
  run:
    dir: "."
  sweeper:
    # optuna_config:
    sampler:
      # _target_: optuna.samplers.RandomSampler
      seed: 123
    direction: minimize
    # study_name: test_x_y_mean_storage_7_2.10.1
    # storage: sqlite:///example.2.10.1-2.db
    study_name: test_x_y_mean_storage_7_3.0.5
    storage: sqlite:///example.3.0.5.db
    n_trials: 5
    n_jobs: 1

experiment:
  name: "exp1"
  rootpath: "artifacts"
  persistent: False
  use_cache: True
  ignore_tags: True
  expand: True
  generation:
    function: "user_functions.generation1"
    params:
      seed: 123
      interval: 0.033
      num_samples: 1
      num_frames: 2
      exposure_time: 0.033
      Nm: [100, 100, 100]
      Dm: [0.222e-12, 0.032e-12, 0.008e-12]
      transmat: [
        [0.0, 0.5, 0.0],
        [0.5, 0.0, 0.2],
        [0.0, 1.0, 0.0]]
  analysis:
    function: "user_functions.analysis1"
    params:
      max_sigma: 4
      min_sigma: 1
      threshold: 50.0
      overlap: 0.5
  evaluation:
    function: "user_functions.evaluation1"
    params:
      max_distance: 5.0
      
